service: miso-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: prod
  httpApi:
    cors: true
functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/server.graphqlHandler # highlight-line
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-plugin-typescript
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${env:CUSTOM_DOMAIN}
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'
    apiType: 'http'
